export const FETCH_ALL_ARTWORK = 'FETCH_ALL_ARTWORK';
export const ADD_SINGLE_ARTWORK = 'ADD_SINGLE_ARTWORK';
export const DELETE_SINGLE_ARTWORK = 'DELETE_SINGLE_ARTWORK';
export const FETCH_AVAILABLE_ARTWORK = 'FETCH_AVAILABLE_ARTWORK';
export const FETCH_ART_IN_CURRENT_MUSEUM = 'FETCH_ART_IN_CURRENT_MUSEUM';
export const UPDATE_MUSEUM_ID_STATUS_OF_ARTWORK = 'UPDATE_MUSEUM_ID_STATUS_OF_ARTWORK';
export const FIND_OLDEST = 'FIND_OLDEST';
